#pragma once
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include <stdio.h>
#include <time.h>
#include <math.h>

#include <SDL2/SDL.h>
#include <SDL2/SDL_ttf.h>
#include "Types.h"
#include "GetInt.h"
#include "Colors.h"
#include "Graphics.h"
#include "Timing.h"
#include "Events.h"
#include "PieceDefs.h"
#include "Board.h"
#include "Pieces.h"
